# Generated by Django 5.2.8 on 2025-12-02 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_session_year_session_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session_year',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='session_year',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='session_year',
            name='session_end',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='session_year',
            name='session_start',
            field=models.CharField(max_length=100),
        ),
    ]
